stages:
  - build
  - docker

build:
  image: node:latest
  stage: build
  script:
    - cp -r web-server ./docker
    - cd app
    - npm install
    - npx expo install react-dom react-native-web @expo/metro-runtime
    - npx expo export --platform web
    - cp -r dist ../docker/web-server
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "release"
  artifacts:
    expire_in: 1 hour
    paths:
      - docker/


docker:
  image: docker:latest
  stage: docker
  services:
    - docker:dind
  needs:
    - build
  script:
    - cd docker
    - docker build -t baldur .
    - docker tag baldur docker.luoja.fr/baldur
    - docker push docker.luoja.fr/baldur
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "release"
